/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ParkingReservation } from "./ParkingReservation";
export * as factories from "./factories";
export { ParkingReservation__factory } from "./factories/ParkingReservation__factory";
