/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ParkingReservationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addParkingSpot"
      | "completeReservation"
      | "getStatistics"
      | "getUserInfo"
      | "isSpotAvailable"
      | "makeReservation"
      | "owner"
      | "parkingSpots"
      | "registerUser"
      | "reservationCounter"
      | "reservations"
      | "totalSpots"
      | "users"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ParkingSpotAdded"
      | "ReservationCompleted"
      | "ReservationCreated"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addParkingSpot",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeReservation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSpotAvailable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeReservation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parkingSpots",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reservationCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reservations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSpots",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "addParkingSpot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeReservation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSpotAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeReservation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parkingSpots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservationCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalSpots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
}

export namespace ParkingSpotAddedEvent {
  export type InputTuple = [
    spotId: BigNumberish,
    location: string,
    pricePerHour: BigNumberish
  ];
  export type OutputTuple = [
    spotId: bigint,
    location: string,
    pricePerHour: bigint
  ];
  export interface OutputObject {
    spotId: bigint;
    location: string;
    pricePerHour: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservationCompletedEvent {
  export type InputTuple = [reservationId: BigNumberish];
  export type OutputTuple = [reservationId: bigint];
  export interface OutputObject {
    reservationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservationCreatedEvent {
  export type InputTuple = [
    reservationId: BigNumberish,
    user: AddressLike,
    spotId: BigNumberish
  ];
  export type OutputTuple = [
    reservationId: bigint,
    user: string,
    spotId: bigint
  ];
  export interface OutputObject {
    reservationId: bigint;
    user: string;
    spotId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    userId: BigNumberish,
    creditScore: BigNumberish
  ];
  export type OutputTuple = [user: string, userId: bigint, creditScore: bigint];
  export interface OutputObject {
    user: string;
    userId: bigint;
    creditScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ParkingReservation extends BaseContract {
  connect(runner?: ContractRunner | null): ParkingReservation;
  waitForDeployment(): Promise<this>;

  interface: ParkingReservationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addParkingSpot: TypedContractMethod<
    [location: string, pricePerHour: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeReservation: TypedContractMethod<
    [reservationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getStatistics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalSpots: bigint;
        _totalReservations: bigint;
        _timestamp: bigint;
      }
    ],
    "view"
  >;

  getUserInfo: TypedContractMethod<
    [userAddress: AddressLike],
    [
      [bigint, bigint, boolean] & {
        userId: bigint;
        creditScore: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;

  isSpotAvailable: TypedContractMethod<
    [spotId: BigNumberish],
    [boolean],
    "view"
  >;

  makeReservation: TypedContractMethod<
    [spotId: BigNumberish, durationHours: BigNumberish],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  parkingSpots: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, string] & {
        location: string;
        pricePerHour: bigint;
        isAvailable: boolean;
        spotOwner: string;
      }
    ],
    "view"
  >;

  registerUser: TypedContractMethod<
    [userId: BigNumberish, creditScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  reservationCounter: TypedContractMethod<[], [bigint], "view">;

  reservations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        spotId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPrice: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  totalSpots: TypedContractMethod<[], [bigint], "view">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        userId: bigint;
        creditScore: bigint;
        isRegistered: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addParkingSpot"
  ): TypedContractMethod<
    [location: string, pricePerHour: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeReservation"
  ): TypedContractMethod<[reservationId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStatistics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalSpots: bigint;
        _totalReservations: bigint;
        _timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [
      [bigint, bigint, boolean] & {
        userId: bigint;
        creditScore: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSpotAvailable"
  ): TypedContractMethod<[spotId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "makeReservation"
  ): TypedContractMethod<
    [spotId: BigNumberish, durationHours: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "parkingSpots"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, string] & {
        location: string;
        pricePerHour: bigint;
        isAvailable: boolean;
        spotOwner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [userId: BigNumberish, creditScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reservationCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reservations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        spotId: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPrice: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSpots"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean, bigint] & {
        userId: bigint;
        creditScore: bigint;
        isRegistered: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ParkingSpotAdded"
  ): TypedContractEvent<
    ParkingSpotAddedEvent.InputTuple,
    ParkingSpotAddedEvent.OutputTuple,
    ParkingSpotAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReservationCompleted"
  ): TypedContractEvent<
    ReservationCompletedEvent.InputTuple,
    ReservationCompletedEvent.OutputTuple,
    ReservationCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ReservationCreated"
  ): TypedContractEvent<
    ReservationCreatedEvent.InputTuple,
    ReservationCreatedEvent.OutputTuple,
    ReservationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "ParkingSpotAdded(uint256,string,uint256)": TypedContractEvent<
      ParkingSpotAddedEvent.InputTuple,
      ParkingSpotAddedEvent.OutputTuple,
      ParkingSpotAddedEvent.OutputObject
    >;
    ParkingSpotAdded: TypedContractEvent<
      ParkingSpotAddedEvent.InputTuple,
      ParkingSpotAddedEvent.OutputTuple,
      ParkingSpotAddedEvent.OutputObject
    >;

    "ReservationCompleted(uint256)": TypedContractEvent<
      ReservationCompletedEvent.InputTuple,
      ReservationCompletedEvent.OutputTuple,
      ReservationCompletedEvent.OutputObject
    >;
    ReservationCompleted: TypedContractEvent<
      ReservationCompletedEvent.InputTuple,
      ReservationCompletedEvent.OutputTuple,
      ReservationCompletedEvent.OutputObject
    >;

    "ReservationCreated(uint256,address,uint256)": TypedContractEvent<
      ReservationCreatedEvent.InputTuple,
      ReservationCreatedEvent.OutputTuple,
      ReservationCreatedEvent.OutputObject
    >;
    ReservationCreated: TypedContractEvent<
      ReservationCreatedEvent.InputTuple,
      ReservationCreatedEvent.OutputTuple,
      ReservationCreatedEvent.OutputObject
    >;

    "UserRegistered(address,uint32,uint16)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
